### ISSUE TITLE
Wandb callback prints errors when a training run resumes not from scratch

### ISSUE THREAD

**Issue by dirkgr** [allenai/tango#152]
It prints
```
wandb: WARNING Step must only increase in log calls.  Step 110 < 161; dropping
```

**Comment by epwalsh** [comment]
This is expected. If, for example, you are checkpointing every 50 steps and your training run crashes after step 212, the last checkpoint will have been at step 200. So when you resume training, you start again from step 201, and W&B will warn you about logging duplicate steps until you get to step 213.

**Comment by dirkgr** [comment]
Why do we even try to log those earlier steps again? Wandb has an option for resuming runs.

**Comment by epwalsh** [comment]
Because the W&B callback that was restored from the checkpoint at step 200 does not know that we actually got to step 212 before crashing.

And we are using the `resume` option. Although after just rereading their docs just now, I think we should set `resume` to "allow" instead of "auto". https://github.com/allenai/tango/pull/155

From their [docs](https://docs.wandb.ai/ref/python/init):

> "auto" (or True): if the preivous run on this machine crashed, automatically resume it. Otherwise, start a new run. - "allow": if id is set with init(id="UNIQUE_ID") or WANDB_RUN_ID="UNIQUE_ID" and it is identical to a previous run, wandb will automatically resume the run with that id. Otherwise, wandb will start a new run. 

"allow" seems a little more robust for our use case, because maybe W&B won't always know when a run crashed (resulting in the "auto" option not working correctly).

**Comment by dirkgr** [comment]
I'm assuming that what wandb wants is to have `resume=auto`, and then the next step we input into wandb is 201. But I think what happens now is that we resume with step 201 correctly, but we tell wandb that it's step 1 (because it's the first step we're actually running).

**Comment by epwalsh** [comment]
> but we tell wandb that it's step 1

No, we tell W&B that it's step 201. W&B complains for the next 12 steps until we get to step 213.

**Comment by dirkgr** [comment]
Ah, interesting. The documentation also says that new values will overwrite the old ones (which would be the right behavior), but the warning message clearly says it's dropping the new information.

**Comment by epwalsh** [comment]
We could probably suppress those warnings though

**Comment by epwalsh** [comment]
> Is there a way we can make it actually overwrite the values?

I don't think so 😕
