### ISSUE TITLE
A Note from a Grateful User

### ISSUE THREAD

**Issue by SimLif** [allenai/tango#567]
### 🚀 The feature, motivation and pitch

Hey everyone, I am a big fan of this project although I have only recently started using it. It saddens me to see that the star rating of this project is increasing slowly, issues are not being addressed promptly, and commits are becoming less frequent. I wanted to write this to let you know that your work is still appreciated, and no matter what some people will continue to support you.

**Comment by Boltzmachine** [comment]
Agree. 
Tango (and maybe AllenNLP) is the **best** framework I've ever used for deep learning.
Obviously it deserves more stars. (although my issues is never replied by anyone)

Wonder if it will still be actively maintained in the future. Or your the team has other considerations (or even switch to another framework)

**Comment by anbasile** [comment]
Same here, big fan of the project. This completely changed how I manage my experiments.

**Comment by wgantt** [comment]
I feel the same.

**Comment by epwalsh** [comment]
Thank you all for the kind words :)

It's true that commits have been much less frequent recently. The core development team, @dirkgr, @AkshitaB, and myself, feel that the library has reached a good stable spot and we've been focusing our efforts on research projects lately, many of which use this library. That's not to say that we won't be adding new features to Tango anymore, just that it's not our main focus (at the moment). We're a small team and we're constantly adjusting our priorities to find a good balance between building tools for research and actually doing research.

But we'll continue to actively maintain it for the foreseeable future, especially since we have many internal users of Tango at AI2.

**Comment by SimLif** [comment]
> Thank you all for the kind words :)
> 
> It's true that commits have been much less frequent recently. The core development team, @dirkgr, @AkshitaB, and myself, feel that the library has reached a good stable spot and we've been focusing our efforts on research projects lately, many of which use this library. That's not to say that we won't be adding new features to Tango anymore, just that it's not our main focus (at the moment). We're a small team and we're constantly adjusting our priorities to find a good balance between building tools for research and actually doing research.
> 
> But we'll continue to actively maintain it for the foreseeable future, especially since we have many internal users of Tango at AI2.

Thank you for clarifying the project's status and sharing your workflow through this open-source project. 

This helps new researchers like me develop code more easily for NLP work. I appreciate you enabling continued progress in the field.  

Wishing you and your team all the best in your research endeavors. Keep up the great work!
